version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4568-4597:4568-4597"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8081}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_EXECUTION_ENV=True
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp"